# -*- coding: utf-8 -*-
"""ASRIN BURGUCU AVENGERS TAŞ KAGIT MAKAS TURNUVASI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18eU3KvOYH2aMEBr2jt4yuRlp3dB0FeKv
"""

## Taş-Kağıt-Makas Turnuvası Kuralları##
##Genel Bilgiler:##
##Bu turnuva dört oyuncu arasında düzenlenir.
## Oyuncuların isimleri şunlardır:##

##Iron_Man
##Thor
##Hulk
##Spider_Man

##Turnuva Yapısı:##

##İlk Tur:

##Oyuncular iki gruba ayrılır:
##Grup 1: Iron_Man ve Thor
##Grup 2: Hulk ve Spider_Man
##Her grup içinde, her oyuncu rakibiyle karşı karşıya gelir.
##Her maçta oyuncular "taş", "kağıt" veya "makas" seçeneğinden birini seçer.
##Bir maçta kazananı belirlemek için:
##Taş kağıdı yener.
##Kağıt makası yener.
##Makas taşı yener.
##Eğer her iki oyuncu aynı seçeneği seçerse, maç berabere biter ve yeniden oynanır.
##İlk iki el kazanan oyuncu, grup içindeki maçları kazanır ve finale yükselir.

##Final Turu:

##Finalde, her iki grup kazananı karşı karşıya gelir.
##Final maçında da oyuncular "taş", "kağıt" veya "makas" seçeneğinden birini seçer.
##Finalde iki el kazanan oyuncu, turnuvayı kazanır.
##Maç ve Final Sonrası:

##Her final maçından sonra, tüm oyunculara oyuna devam etmek isteyip istemedikleri sorulur.
##Her oyuncu tek tek yanıtlar:
##Eğer tüm oyuncular "evet" derse, oyun tekrar başlatılır ve turnuva yeniden oynanır.
##Eğer herhangi bir oyuncu "hayır" derse, turnuva sona erer.
##Önemli Notlar:
##Her maçta ve finalde, oyuncuların seçimleri rastgele belirlenir.
##Oyuncuların seçimleri ve kazananları belirleyen fonksiyon, standart taş-kağıt-makas kurallarına göre çalışır.
##Oyun sırasında her oyuncunun el kazandığı sayılar dikkatlice takip edilir.
##Turnuvanın sonunda kazanan oyuncu ilan edilir.
## Turnuva keyifli ve adil bir şekilde oynanmalıdır. İyi şanslar!##

import random

def tas_kagit_makas_ASRIN_BURGUCU():
    oyuncular = ["Iron_Man", "Thor", "Hulk", "Spider_Man"]
    secenekler = ["taş", "kağıt", "makas"]

    def kazanan_belirle(secimler):
        kazananlar = []

        tas_sayisi = list(secimler.values()).count("taş")
        kagit_sayisi = list(secimler.values()).count("kağıt")
        makas_sayisi = list(secimler.values()).count("makas")

        if tas_sayisi > 0 and kagit_sayisi > 0 and makas_sayisi > 0:
            return "Berabere! Tüm seçenekler var.", None
        elif tas_sayisi > 0 and kagit_sayisi > 0:
            kazananlar = [k for k, v in secimler.items() if v == "kağıt"]
        elif kagit_sayisi > 0 and makas_sayisi > 0:
            kazananlar = [k for k, v in secimler.items() if v == "makas"]
        elif makas_sayisi > 0 and tas_sayisi > 0:
            kazananlar = [k for k, v in secimler.items() if v == "taş"]

        if len(kazananlar) == 0:
            return "Berabere! Herkes aynı şeyi seçti.", None
        else:
            return f"Kazanan: {', '.join(kazananlar)}", kazananlar

    def oynat_grup(grup):
        el_sayilari = {oyuncu: 0 for oyuncu in grup}
        while True:
            secimler = {}
            for oyuncu in grup:
                secimler[oyuncu] = random.choice(secenekler)
                print(f"{oyuncu} seçimi: {secimler[oyuncu]}")

            sonuc, kazananlar = kazanan_belirle(secimler)
            print(sonuc)

            if kazananlar:
                for kazanan in kazananlar:
                    el_sayilari[kazanan] += 1

            print("El Sayıları:")
            for oyuncu, el in el_sayilari.items():
                print(f"{oyuncu}: {el} el kazandı.")

            for oyuncu, el in el_sayilari.items():
                if el == 2:
                    print(f"\n{oyuncu} bu grupta kazandı ve finale çıktı!")
                    return oyuncu

    while True:
        # İlk tur: Grupları oynatıyoruz
        print("İlk Tur Başlıyor!")
        grup_1 = oyuncular[:2]  # İlk iki oyuncu
        grup_2 = oyuncular[2:]  # Son iki oyuncu

        final_1 = oynat_grup(grup_1)
        final_2 = oynat_grup(grup_2)

        # Final turu
        print("\nFinal Turu Başlıyor!")
        final_grubu = [final_1, final_2]
        final_kazanan = oynat_grup(final_grubu)

        print(f"\nFinali kazanan: {final_kazanan}!")

        # Finalden sonra tüm oyunculara oyuna devam etmek isteyip istemediklerini sor
        devam_edilecek = True
        for oyuncu in oyuncular:
            devam = input(f"{oyuncu}, oyuna devam etmek ister misiniz? (Evet/Hayır): ").lower()
            if devam != 'evet':
                devam_edilecek = False
                print(f"{oyuncu} oyundan çıktı.")
                break

        if devam_edilecek:
            print("Tüm oyuncular oyuna devam ediyor. Oyun tekrar başlatılıyor!\n")
        else:
            print("Oyun sona erdi!")
            break

# Oyunu başlatmak için fonksiyonu çağır
tas_kagit_makas_ASRIN_BURGUCU()